version: '3'

services:
  db:
    image: public.ecr.aws/aws-dynamodb-local/aws-dynamodb-local:latest
    restart: always
    container_name: pagamento_dbhost
    environment:
      - AWS_ACCESS_KEY_ID=pagamento_db
      - AWS_SECRET_ACCESS_KEY=dynamo
      - REGION=us-east-2
    ports:
      - 5435:5432
