version: '3'

services:
  db:
    image: public.ecr.aws/aws-dynamodb-local/aws-dynamodb-local:latest
    restart: always
    container_name: pagamento_dbhost
    environment:
      - DYNAMODB_DB=pagamento_db
      - DYNAMODB_USER=dynamo
      - DYNAMODB_PASSWORD=dynamo
    ports:
      - 5435:5432
