version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pagamento_app
    restart: always
    ports:
      - 8083:8080
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pagamento_dbhost:5432/pagamento_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: postgres:15
    restart: always
    container_name: pagamento_dbhost
    environment:
      - POSTGRES_DB=pagamento_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5435:5432
