version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pagamentos
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - AWS_REGION=us-east-2
      - AWS_DYNAMODB_ENDPOINT=xxx
      - AWS_ACCESS_KEY=xxx

  db:
    image: public.ecr.aws/aws-dynamodb-local/aws-dynamodb-local:latest
    restart: always
    container_name: db
    ports:
      - 5432:5432
