version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pagamento_app
    restart: always
    ports:
      - 8083:8080
    environment:
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_DYNAMODB_ENDPOINT=${AWS_DYNAMODB_ENDPOINT}
