version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pagamento_app
    restart: always
    ports:
      - 8083:8080
    depends_on:
      - db
    environment:
      - AWS_REGION=us-east-2
      - AWS_DYNAMODB_ENDPOINT=xxx
      - AWS_ACCESS_KEY=xxx
      - AWS_SECRET_ACCESS_KEY=xxx

  db:
    image: public.ecr.aws/aws-dynamodb-local/aws-dynamodb-local:latest
    restart: always
    container_name: pagamento_dbhost
    environment:
      AWS_ACCESS_KEY_ID: 'xxx'
      AWS_SECRET_ACCESS_KEY: 'xxx'
      REGION: 'us-east-2'
    ports:
      - 5435:5432
