package br.com.fiap.soat.pagamentos.dynamodb.entities;

import br.com.fiap.soat.pagamentos.entities.Pagamento;
import br.com.fiap.soat.pagamentos.entities.Status;
import com.amazonaws.services.dynamodbv2.datamodeling.*;

import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbAttribute;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbBean;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbPartitionKey;

import java.math.BigDecimal;

@DynamoDbBean
@DynamoDBTable(tableName = "Pagamentos")
public class PagamentoDynamoEntity {
    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute(attributeName = "pedidoId")
    private String pedidoId;

    @DynamoDBAttribute(attributeName = "total")
    private BigDecimal total;

    @DynamoDBAttribute(attributeName = "status")
    @DynamoDBTypeConverted(converter = StatusConverter.class)
    private Status status;

    @DynamoDBAttribute(attributeName = "dataDeCriacao")
    private String dataDeCriacao;

    @DynamoDbPartitionKey
    @DynamoDbAttribute("id")
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDbAttribute("status")
    public Status getStatus() {
        return status;
    }

    public void setStatus(Status status) {
        this.status = status;
    }

    @DynamoDbAttribute("pedidoId")
    public String getPedidoId() {
        return pedidoId;
    }

    public void setPedidoId(String pedidoId) {
        this.pedidoId = pedidoId;
    }

    @DynamoDbAttribute("total")
    public BigDecimal getTotal() {
        return total;
    }

    public void setTotal(BigDecimal total) {
        this.total = total;
    }

    @DynamoDbAttribute("dataDeCriacao")
    public String getDataDeCriacao() {
        return dataDeCriacao;
    }

    public void setDataDeCriacao(String dataDeCriacao) {
        this.dataDeCriacao = dataDeCriacao;
    }

    public static PagamentoDynamoEntity fromDomain(Pagamento pagamento) {
        PagamentoDynamoEntity dynamoEntity = new PagamentoDynamoEntity();

        dynamoEntity.setId(pagamento.getId());
        dynamoEntity.setPedidoId(pagamento.getPedidoId());
        dynamoEntity.setTotal(pagamento.getTotal());
        dynamoEntity.setStatus(pagamento.getStatus());
        dynamoEntity.setDataDeCriacao(pagamento.getDataDeCriacao());

        return dynamoEntity;
    }

    public Pagamento toDomain() {
        return new Pagamento(
                id,
                pedidoId,
                total,
                status,
                dataDeCriacao
        );
    }

    public static class StatusConverter implements DynamoDBTypeConverter<String, Status> {
        @Override
        public String convert(Status status) {
            return status.name();
        }

        @Override
        public Status unconvert(String value) {
            return Status.valueOf(value);
        }
    }
}
