package br.com.fiap.soat.pagamentos.dynamodb.entities;

import br.com.fiap.soat.pagamentos.entities.Pagamento;
import br.com.fiap.soat.pagamentos.entities.Status;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbAttribute;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbBean;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbPartitionKey;

import java.math.BigDecimal;
import java.util.UUID;

@DynamoDbBean
@DynamoDBTable(tableName = "pagamentos")
public class PagamentoDynamoEntity {
    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private UUID id;

    @DynamoDBAttribute(attributeName = "pedidoId")
    private UUID pedidoId;

    @DynamoDBAttribute(attributeName = "total")
    private BigDecimal total;

    @DynamoDBAttribute(attributeName = "status")
    private Status status;

    @DynamoDBAttribute(attributeName = "dataDeCriacao")
    private String dataDeCriacao;

    @DynamoDbPartitionKey
    @DynamoDbAttribute("id")
    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    @DynamoDbAttribute("status")
    public Status getStatus() {
        return status;
    }

    public void setStatus(Status status) {
        this.status = status;
    }

    @DynamoDbAttribute("pedidoId")
    public UUID getPedidoId() {
        return pedidoId;
    }

    public void setPedidoId(UUID pedidoId) {
        this.pedidoId = pedidoId;
    }

    @DynamoDbAttribute("total")
    public BigDecimal getTotal() {
        return total;
    }

    public void setTotal(BigDecimal total) {
        this.total = total;
    }

    @DynamoDbAttribute("dataDeCriacao")
    public String getDataDeCriacao() {
        return dataDeCriacao;
    }

    public void setDataDeCriacao(String dataDeCriacao) {
        this.dataDeCriacao = dataDeCriacao;
    }

    public PagamentoDynamoEntity() {
        this.id = UUID.randomUUID();
    }

    public static PagamentoDynamoEntity fromDomain(Pagamento pagamento) {
        PagamentoDynamoEntity dynamoEntity = new PagamentoDynamoEntity();

        dynamoEntity.setId(pagamento.getId());
        dynamoEntity.setPedidoId(pagamento.getPedidoId());
        dynamoEntity.setTotal(pagamento.getTotal());
        dynamoEntity.setStatus(pagamento.getStatus());
        dynamoEntity.setDataDeCriacao(pagamento.getDataDeCriacao());

        return dynamoEntity;
    }

    public Pagamento toDomain() {
        return new Pagamento(
                id,
                pedidoId,
                total,
                status,
                dataDeCriacao
        );
    }
}
