apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-pedido
  labels:
    name: ms-pedido
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-pedido
  template:
    metadata:
      labels:
        app: ms-pedido
    spec:
      containers:
      - name: ms-pedido
        image: pabloldias/soat1-grupo18-ms-pedido:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "256Mi"
            cpu: "125m"
          limits:
            memory: "512Mi"
            cpu: "2000m"
        env:
        - name: SERVER_PORT
          value: "8080"
        ports:
        - containerPort: 8080
