apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-pagamento
  labels:
    name: ms-pagamento
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-pagamento
  template:
    metadata:
      labels:
        app: ms-pagamento
    spec:
      containers:
      - name: ms-pagamento
        image: pabloldias/soat1-grupo18-ms-pagamento:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "384Mi"
            cpu: "2000m"
        env:
        - name: SERVER_PORT
          value: "8080"
        - name: AWS_REGION
          value: "sa-east-1"
        - name: AWS_DYNAMODB_ENDPOINT
          value: "dynamodb.sa-east-1.amazonaws.com"
        - name: AWS_ACCESS_KEY
          valueFrom:
            name: aws-credentials
            key: aws_access_key
        - name: AWS_SECRET_KEY
          valueFrom:
            name: aws-credentials
            key: aws_secret_key
        ports:
        - containerPort: 8080
