apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: aws-credentials
stringData: # FIXME: add actual credentials
  AWS_SECRET_ACCESS_KEY: invalid-credentials
  AWS_ACCESS_KEY_ID: invalid-credentials