name: Build and test

on:
  pull_request:
    branches:
      - 'main'

permissions:
  id-token: write
  contents: read

jobs:
  infrastructure:
    uses: soat1-grupo18/fase4-reusable-github-workflows/.github/workflows/aws-terraform.yml@main
    with:
      aws-region: us-east-1
      terraform-directory-path: infrastructure
      terraform-version: 1.7.0
    secrets: inherit

  java-microservice:
    needs:
      - infrastructure
    uses: soat1-grupo18/fase4-reusable-github-workflows/.github/workflows/java-microservice.yml@main
    with:
      application-name: soat1-grupo18-ms-pagamento
      java-distribution: corretto
      java-version: "17"
      kubernetes-cluster-name: fiap-cluster
      kubernetes-manifest-directory-path: kubernetes
      kubernetes-namespace: ms-pagamento
    secrets: inherit

  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
