name: Build and test

on:
  pull_request:
    branches:
      - 'main'

permissions:
  id-token: write
  contents: read

jobs:
  infrastructure:
    uses: soat1-grupo18/fase4-reusable-github-workflows/.github/workflows/aws-terraform.yml@main
    with:
      aws-region: us-east-1
      terraform-directory-path: infrastructure
      terraform-version: 1.7.0
    secrets: inherit

  java-microservice:
    needs:
      - infrastructure
    uses: soat1-grupo18/fase4-reusable-github-workflows/.github/workflows/java-microservice.yml@main
    with:
      application-name: soat1-grupo18-ms-pagamento
      java-distribution: corretto
      java-version: "17"
      kubernetes-cluster-name: fiap-cluster
      kubernetes-manifest-directory-path: kubernetes
      kubernetes-namespace: ms-pagamento
    secrets: inherit

  build-and-test-java:
    name: Compile and Test Java
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
      - run: ./mvnw test
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: target/site/jacoco/jacoco.xml

  sonarCloudTrigger-java:
    needs: build-and-test-java
    name: SonarCloud Trigger Java
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Download code coverage results
        uses: actions/download-artifact@v2
        with:
          name: code-coverage-report
          path: target/site/jacoco/jacoco.xml
      - name: Analyze with SonarCloud Java
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}