name: Build and test

on:
  pull_request:
    branches:
      - 'main'

jobs:
  microservices-deploy:
    uses: soat1-grupo18/fase3-reusable-github-workflows/.github/workflows/microservices-deploy.yml@main
    with:
      microservice-id: soat1-grupo18-ms-pagamento
    secrets: inherit